import { formatDate, INTERVIEW_TYPE_LABELS } from '@/lib/utils'
import type { ReportRecommendation, ReportTheme } from '@/types'

export function BroadcastPrintReport({ report, interview, persona, profile }: { report: any; interview: any; persona: any; profile: any }) {
  const themes: ReportTheme[] = report.key_themes ?? []
  const recommendations: ReportRecommendation[] = report.recommendations ?? []
  const accent = profile?.brand_color || '#516258'
  const title = interview?.title || 'Strategic Research Insights'
  return <article className="broadcast-print-only" style={{ ['--broadcast-accent' as string]: accent }}>
    <section className="broadcast-cover"><div className="broadcast-cover-mark" />
      <div className="broadcast-logo">{profile?.brand_logo_url ? <img src={profile.brand_logo_url} alt="Client logo" /> : <span>{profile?.full_name || 'CLIENT LOGO'}</span>}</div>
      <span className="broadcast-label">White-label premium</span><h1>Strategic Research<br />Insights</h1><p className="broadcast-cover-title">{title}</p>
      <div className="broadcast-cover-meta"><div><small>Prepared by</small><strong>{profile?.full_name || 'SignalRoom Intelligence Unit'}</strong></div><i /><div><small>Publication date</small><strong>{formatDate(report.created_at)}</strong></div></div>
    </section>
    <main className="broadcast-document">
      <section className="broadcast-brief"><header><h2>Decision Brief</h2><span>Strategic level: Executive</span></header><div className="broadcast-brief-body"><div className="broadcast-brief-grid"><div><h3>The core challenge</h3><p className="broadcast-italic">{report.ai_verdict?.summary || report.executive_summary}</p></div><div><h3>Primary opportunity</h3><p>{recommendations[0]?.detail || 'Turn the strongest research signal into a focused next action.'}</p></div></div><p className="broadcast-summary">{report.executive_summary}</p></div></section>
      <section className="broadcast-scope"><Scope label="Participants" value="01 Primary Persona" detail={`${persona?.name || 'Target persona'} perspective`} /><Scope label="Methodology" value={INTERVIEW_TYPE_LABELS[interview?.type] || 'In-depth interview'} detail="Qualitative research synthesis" /><Scope label="Analysis window" value={formatDate(report.created_at)} detail="SignalRoom intelligence report" /></section>
      {themes.length > 0 && <section className="broadcast-themes"><h2>Core Strategic Pillars</h2>{themes.map((theme, index) => <div className="broadcast-theme" key={index}><div className="broadcast-theme-head"><span>{String(index + 1).padStart(2, '0')}</span><div><h3>{theme.title}</h3><em>{theme.sentiment} signal</em></div></div><p>{theme.summary}</p>{theme.quotes?.[0] && <blockquote>{theme.quotes[0]}</blockquote>}</div>)}</section>}
      {recommendations[0] && <section className="broadcast-recommendation"><small>Top recommendation</small><h2>{recommendations[0].title}</h2><p>{recommendations[0].detail}</p></section>}
      <section className="broadcast-footer"><div><strong>Confidential | Client report</strong><span>Generated by SignalRoom Intelligence Unit · Document ID: SR-{report.id.slice(0, 8).toUpperCase()}</span></div><div><small>Classification</small><strong>External executive</strong></div></section>
    </main>
  </article>
}
function Scope({ label, value, detail }: { label: string; value: string; detail: string }) { return <div><small>{label}</small><strong>{value}</strong><p>{detail}</p></div> }
