import { notFound } from 'next/navigation'
import Link from 'next/link'
import { createClient as createSupabaseClient } from '@supabase/supabase-js'
import {
  formatDate,
  getPriorityColor,
  INTERVIEW_TYPE_LABELS,
  CARD_SHADOW,
} from '@/lib/utils'
import { HOME_COLORS, HOME_FONT_DISPLAY, HOME_FONT_BODY, DISPLAY_LG_STYLE } from '@/lib/home-theme'
import {
  ArrowDown,
  TrendingUp,
  AlertCircle,
  CheckCircle2,
  Info,
  Sparkles,
} from 'lucide-react'
import { PersonaAvatar } from '@/components/persona/PersonaAvatar'
import { DownloadReportButton } from '@/components/ui/DownloadReportButton'
import { CopyLinkButton } from '@/components/ui/CopyLinkButton'
import { ThemesClient } from '@/app/(dashboard)/reports/[id]/ThemesClient'
import { PLAN_LIMITS } from '@/types'
import type { Persona, Plan, ReportTheme, ReportRecommendation } from '@/types'

const cardStyle = { background: HOME_COLORS.surfaceContainerLowest, boxShadow: CARD_SHADOW }

// Shared reports are unlisted links — keep them out of search indexes.
export const metadata = {
  robots: { index: false, follow: false },
}

export default async function PublicReportPage({ params }: { params: Promise<{ id: string }> }) {
  // The URL segment is a share token, not the report id. Reports without a
  // token (the default) are not reachable here at all; revoking the token
  // makes previously copied links 404.
  const { id: token } = await params

  // Use service role key — server component only, never reaches browser
  // Bypasses RLS for this single query without exposing data publicly via anon policies
  const supabase = createSupabaseClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  )

  const { data: report, error } = await supabase
    .from('reports')
    .select(`
      *,
      interview:interviews(
        id, title, type, context, messages, created_at,
        persona:personas(*)
      )
    `)
    .eq('share_token', token)
    .single()

  if (error || !report) notFound()

  // White-label (Broadcast): the report OWNER's plan controls whether the
  // SignalRoom logo/upsell shows on their shared links — an agency handing a
  // client a report link shouldn't be advertising SignalRoom on their work.
  // For a workspace report, "owner" means the workspace owner, not
  // report.user_id — the report may have been generated by a teammate who
  // personally is on any plan (even Free), operating under the workspace
  // owner's Broadcast entitlement.
  let planCheckUserId = report.user_id
  if (report.workspace_id) {
    const { data: workspace } = await supabase
      .from('workspaces')
      .select('owner_id')
      .eq('id', report.workspace_id)
      .single()
    if (workspace) planCheckUserId = workspace.owner_id
  }

  const { data: ownerProfile } = await supabase
    .from('profiles')
    .select('plan, full_name, brand_logo_url, brand_color')
    .eq('id', planCheckUserId)
    .single()
  const ownerPlan = (ownerProfile?.plan ?? 'free') as Plan
  const isWhiteLabel = PLAN_LIMITS[ownerPlan]?.white_label ?? false

  // Beyond hiding SignalRoom's own branding, genuine white-label means
  // showing the AGENCY's branding — a custom logo and accent color, so the
  // report reads as their own deliverable. Falls back to today's look
  // (SignalRoom's brand accent, no logo) if the owner hasn't set one yet.
  const brandLogoUrl = isWhiteLabel ? ownerProfile?.brand_logo_url : null
  const accentColor = (isWhiteLabel && ownerProfile?.brand_color) || HOME_COLORS.primary
  const brandName = ownerProfile?.full_name?.trim() || 'Private research'

  const interview = report.interview
  const persona = interview?.persona

  const score = report.confidence_score
  const scoreColor = score >= 75 ? accentColor : score >= 50 ? '#B45309' : HOME_COLORS.error
  const scoreBg = score >= 75 ? HOME_COLORS.secondaryContainer : score >= 50 ? '#FEF3C7' : '#FFDAD6'
  const scoreLabel = score >= 75 ? 'High Confidence' : score >= 50 ? 'Moderate Confidence' : 'Low Confidence'

  const themes: ReportTheme[] = report.key_themes ?? []
  const recommendations: ReportRecommendation[] = report.recommendations ?? []
  const messageCount = interview?.messages?.length ?? 0
  const reportDate = formatDate(report.created_at)
  const accentWash = withAlpha(accentColor, 0.1)
  const accentLine = withAlpha(accentColor, 0.28)

  return (
    <div
      style={{
        background: isWhiteLabel
          ? `radial-gradient(circle at 88% 4%, ${accentWash} 0, transparent 28rem), ${HOME_COLORS.surface}`
          : HOME_COLORS.surface,
        fontFamily: HOME_FONT_BODY,
        minHeight: '100vh',
      }}
    >
      <div className="p-4 sm:p-8 max-w-4xl mx-auto">

        {/* Public header — SignalRoom's own branding for everyone else; the
            agency's own logo (if they've set one) for white-label accounts;
            nothing at all for white-label accounts with no logo uploaded yet */}
        {!isWhiteLabel && (
          <div className="flex items-center justify-between mb-6">
            <Link href="https://getsignalroom.com" className="flex items-center transition-opacity hover:opacity-80">
              <img src="/signalroom-logo.svg" alt="SignalRoom" width="94" height="55" className="h-12 w-auto object-contain" />
            </Link>
            <Link
              href="/signup"
              className="text-xs font-semibold px-4 py-2 rounded-full transition-opacity hover:opacity-90"
              style={{ background: HOME_COLORS.primary, color: HOME_COLORS.onPrimary }}
            >
              Try SignalRoom free →
            </Link>
          </div>
        )}
        {isWhiteLabel && brandLogoUrl && (
          <div className="flex items-center mb-6">
            {/* eslint-disable-next-line @next/next/no-img-element -- tenant-provided Supabase logo URL */}
            <img src={brandLogoUrl} alt={`${brandName} logo`} className="h-10 w-auto object-contain" />
          </div>
        )}

        {/* Broadcast presentation cover. It intentionally only exists on the
            white-label path: Signal reports retain their established layout. */}
        {isWhiteLabel && (
          <section
            className="relative overflow-hidden rounded-[28px] px-6 py-8 mb-5 sm:px-9 sm:py-11"
            style={{ background: HOME_COLORS.surfaceContainerLowest, boxShadow: CARD_SHADOW, border: `1px solid ${accentLine}` }}
          >
            <div className="absolute top-0 left-0 h-1 w-full" style={{ background: accentColor }} />
            <div className="flex flex-wrap items-center justify-between gap-3 mb-10">
              <span className="text-[10px] font-semibold uppercase tracking-[0.22em]" style={{ color: accentColor }}>Confidential research brief</span>
              <span className="text-[10px] font-medium uppercase tracking-[0.16em]" style={{ color: HOME_COLORS.onSurfaceVariant }}>{reportDate}</span>
            </div>
            <div className="max-w-2xl">
              <p className="text-xs mb-3" style={{ color: HOME_COLORS.onSurfaceVariant }}>Prepared for decision-makers</p>
              <h1 className="mb-4" style={{ ...DISPLAY_LG_STYLE, fontSize: 'clamp(30px, 5vw, 48px)', lineHeight: 1.06, color: HOME_COLORS.onSurface }}>
                {interview?.title ?? 'Untitled research brief'}
              </h1>
              {interview?.context && (
                <p className="max-w-xl text-sm leading-relaxed" style={{ color: HOME_COLORS.onSurfaceVariant }}>{interview.context}</p>
              )}
            </div>
            <div className="mt-9 grid grid-cols-2 gap-y-5 border-t pt-6 sm:grid-cols-4" style={{ borderColor: accentLine }}>
              <CoverMetric label="Research format" value={INTERVIEW_TYPE_LABELS[interview?.type] ?? 'Interview'} />
              <CoverMetric label="Perspective" value={persona?.name ?? 'Persona'} />
              <CoverMetric label="Key themes" value={String(themes.length)} />
              <CoverMetric label="Recommendations" value={String(recommendations.length)} />
            </div>
          </section>
        )}

        {isWhiteLabel && (
          <nav aria-label="Report sections" className="no-print mb-6 flex flex-wrap items-center gap-x-5 gap-y-2 px-1 text-[11px] font-semibold uppercase tracking-[0.12em]" style={{ color: accentColor }}>
            <a href="#overview" className="transition-opacity hover:opacity-65">Overview</a>
            {themes.length > 0 && <a href="#themes" className="transition-opacity hover:opacity-65">Themes</a>}
            {recommendations.length > 0 && <a href="#recommendations" className="transition-opacity hover:opacity-65">Recommendations</a>}
            <a href="#methodology" className="transition-opacity hover:opacity-65">Research scope</a>
            <a href="#report-end" className="ml-auto inline-flex items-center gap-1 transition-opacity hover:opacity-65">Read report <ArrowDown size={12} /></a>
          </nav>
        )}

        {/* Report header */}
        <div id="overview" className="rounded-2xl p-4 sm:p-6 mb-6" style={isWhiteLabel ? { ...cardStyle, borderTop: `3px solid ${accentColor}` } : cardStyle}>
          <div className="flex flex-col sm:flex-row items-start sm:justify-between gap-4 sm:gap-6">
            <div className="flex items-start gap-4">
              <PersonaAvatar avatarUrl={persona?.avatar_url} avatarInitials={persona?.avatar_initials} avatarColor={persona?.avatar_color} name={persona?.name} size="lg" />
              <div className="min-w-0">
                <h1 className="mb-0.5" style={{ ...DISPLAY_LG_STYLE, fontSize: '22px', lineHeight: '28px', color: HOME_COLORS.onSurface }}>
                  {interview?.title ?? 'Untitled interview'}
                </h1>
                <p className="text-sm" style={{ color: HOME_COLORS.onSurfaceVariant }}>
                  {persona?.name} · {INTERVIEW_TYPE_LABELS[interview?.type] ?? 'Interview'} · {formatDate(report.created_at)}
                </p>
                {interview?.context && (
                  <p className="text-xs mt-2 max-w-lg leading-relaxed" style={{ color: HOME_COLORS.onSurfaceVariant }}>
                    <span className="font-medium">Tested: </span>
                    {interview.context}
                  </p>
                )}
              </div>
            </div>

            {/* Confidence score badge */}
            <div className="flex-shrink-0 text-center rounded-xl px-4 py-3 self-start sm:self-auto" style={{ background: isWhiteLabel && score >= 75 ? accentWash : scoreBg }}>
              <p className="text-3xl font-semibold leading-none" style={{ fontFamily: HOME_FONT_DISPLAY, color: scoreColor }}>{score}</p>
              <p className="text-[11px] font-semibold mt-1 uppercase tracking-wider" style={{ color: scoreColor }}>{scoreLabel}</p>
              <p className="text-[10px] mt-0.5" style={{ color: HOME_COLORS.onSurfaceVariant }}>Confidence Score</p>
            </div>
          </div>

          {/* Stats row */}
          <div className="flex flex-wrap items-center gap-4 sm:gap-6 mt-5 pt-5" style={{ borderTop: `1px solid ${HOME_COLORS.outlineVariant}4d` }}>
            <div>
              <p className="text-lg font-semibold" style={{ color: HOME_COLORS.onSurface }}>{themes.length}</p>
              <p className="text-xs" style={{ color: HOME_COLORS.onSurfaceVariant }}>Key themes</p>
            </div>
            <div>
              <p className="text-lg font-semibold" style={{ color: HOME_COLORS.onSurface }}>{recommendations.length}</p>
              <p className="text-xs" style={{ color: HOME_COLORS.onSurfaceVariant }}>Recommendations</p>
            </div>
            <div>
              <p className="text-lg font-semibold" style={{ color: HOME_COLORS.onSurface }}>{messageCount}</p>
              <p className="text-xs" style={{ color: HOME_COLORS.onSurfaceVariant }}>Messages</p>
            </div>
            <div className="flex items-center gap-3 sm:ml-auto w-full sm:w-auto">
              <DownloadReportButton />
              <CopyLinkButton />
            </div>
          </div>
        </div>

        {/* AI Verdict */}
        {report.ai_verdict && (
          <div className="rounded-2xl p-5 mb-6" style={{ background: isWhiteLabel ? accentWash : HOME_COLORS.primaryFixed, border: isWhiteLabel ? `1px solid ${accentLine}` : undefined }}>
            <div className="flex items-center gap-2 mb-3">
              <Sparkles size={15} style={{ color: isWhiteLabel ? accentColor : HOME_COLORS.onPrimaryFixed }} />
              <h2 className="text-[11px] font-semibold uppercase tracking-wider" style={{ color: isWhiteLabel ? accentColor : HOME_COLORS.onPrimaryFixed }}>
                {isWhiteLabel ? 'Decision brief' : 'AI Verdict'}
              </h2>
            </div>
            <p className="text-sm leading-relaxed" style={{ color: isWhiteLabel ? HOME_COLORS.onSurface : HOME_COLORS.onPrimaryFixed }}>{report.ai_verdict.summary}</p>
            <div className="mt-4 pt-4 space-y-2" style={{ borderTop: `1px solid ${isWhiteLabel ? accentLine : `${HOME_COLORS.onPrimaryFixedVariant}33`}` }}>
              <p className="text-xs leading-relaxed" style={{ color: isWhiteLabel ? HOME_COLORS.onSurface : HOME_COLORS.onPrimaryFixed }}>
                <span className="font-semibold">Validate next: </span>{report.ai_verdict.validate_next}
              </p>
              <p className="text-xs leading-relaxed" style={{ color: isWhiteLabel ? HOME_COLORS.onSurface : HOME_COLORS.onPrimaryFixed }}>
                <span className="font-semibold">Ask real users: </span>&ldquo;{report.ai_verdict.follow_up_question}&rdquo;
              </p>
            </div>
          </div>
        )}

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="lg:col-span-2 space-y-5">

            {/* Executive summary */}
            <div className="rounded-2xl p-5" style={cardStyle}>
              <div className="flex items-center gap-2 mb-3">
                <TrendingUp size={15} style={{ color: HOME_COLORS.onSurfaceVariant }} />
                <h2 className="text-[11px] font-semibold uppercase tracking-wider" style={{ color: isWhiteLabel ? accentColor : HOME_COLORS.onSurfaceVariant }}>
                  Executive summary
                </h2>
              </div>
              <p className="text-sm leading-relaxed" style={{ color: HOME_COLORS.onSurface }}>{report.executive_summary}</p>
            </div>

            {/* Key themes */}
            {themes.length > 0 && (
              <div id="themes" className="space-y-3 scroll-mt-6">
                <h2 className="text-[11px] font-semibold uppercase tracking-wider" style={{ color: isWhiteLabel ? accentColor : HOME_COLORS.onSurfaceVariant }}>
                  Key themes
                </h2>
                <ThemesClient themes={themes} confidenceScore={score} />
              </div>
            )}

            {/* Recommendations */}
            {recommendations.length > 0 && (
              <div id="recommendations" className="space-y-3 scroll-mt-6">
                <h2 className="text-[11px] font-semibold uppercase tracking-wider" style={{ color: isWhiteLabel ? accentColor : HOME_COLORS.onSurfaceVariant }}>
                  Recommendations
                </h2>
                {recommendations.map((rec, i) => (
                  <RecommendationCard key={i} rec={rec} accentColor={isWhiteLabel ? accentColor : undefined} />
                ))}
              </div>
            )}
          </div>

          {/* Right sidebar */}
          <div className="space-y-5">

            {/* Confidence explainer */}
            <div className="rounded-2xl p-4" style={cardStyle}>
              <div className="flex items-center gap-2 mb-3">
                <Info size={13} style={{ color: HOME_COLORS.onSurfaceVariant }} />
                <h3 className="text-[11px] font-semibold uppercase tracking-wider" style={{ color: HOME_COLORS.onSurfaceVariant }}>About this score</h3>
              </div>
              <div className="space-y-2.5">
                <ConfidenceBar label="Depth of responses" value={Math.min(100, messageCount * 12)} accentColor={accentColor} />
                <ConfidenceBar label="Persona specificity" value={getPersonaSpecificity(persona)} accentColor={accentColor} />
              </div>
              <p className="text-xs mt-3 leading-relaxed" style={{ color: HOME_COLORS.onSurfaceVariant }}>
                This score measures the depth and specificity of this AI interview session — not market certainty. Longer sessions with a well-defined persona score higher. Always validate key findings with real users.
              </p>
            </div>

            {/* Sentiment breakdown */}
            {themes.length > 0 && (
              <div className="rounded-2xl p-4" style={cardStyle}>
                <h3 className="text-[11px] font-semibold uppercase tracking-wider mb-3" style={{ color: HOME_COLORS.onSurfaceVariant }}>
                  Sentiment breakdown
                </h3>
                <SentimentBreakdown themes={themes} accentColor={accentColor} />
              </div>
            )}

            {/* Persona summary */}
            {persona && (
              <div className="rounded-2xl p-4" style={cardStyle}>
                <h3 className="text-[11px] font-semibold uppercase tracking-wider mb-3" style={{ color: HOME_COLORS.onSurfaceVariant }}>
                  Interviewed
                </h3>
                <div className="flex items-center gap-2.5 mb-3">
                  <PersonaAvatar avatarUrl={persona.avatar_url} avatarInitials={persona.avatar_initials} avatarColor={persona.avatar_color} name={persona.name} size="sm" />
                  <div>
                    <p className="text-sm font-semibold" style={{ color: HOME_COLORS.onSurface }}>{persona.name}</p>
                    <p className="text-xs" style={{ color: HOME_COLORS.onSurfaceVariant }}>{persona.traits?.job_title}</p>
                  </div>
                </div>
                <dl className="space-y-1.5">
                  {[
                    ['Age', persona.traits?.age],
                    ['Location', persona.traits?.location],
                    ['Industry', persona.traits?.industry],
                  ].filter(([, v]) => v).map(([label, value]) => (
                    <div key={String(label)} className="flex justify-between">
                      <dt className="text-xs" style={{ color: HOME_COLORS.onSurfaceVariant }}>{label}</dt>
                      <dd className="text-xs font-medium" style={{ color: HOME_COLORS.onSurface }}>{value}</dd>
                    </div>
                  ))}
                </dl>
                <Link href={`/personas/${persona.id}`} className="block text-xs mt-3 transition-colors" style={{ color: accentColor }}>
                  View full persona →
                </Link>
              </div>
            )}

            {isWhiteLabel && (
              <div id="methodology" className="rounded-2xl p-4 scroll-mt-6" style={{ ...cardStyle, borderTop: `2px solid ${accentColor}` }}>
                <h3 className="text-[11px] font-semibold uppercase tracking-wider mb-3" style={{ color: accentColor }}>Research scope</h3>
                <dl className="space-y-2 text-xs" style={{ color: HOME_COLORS.onSurfaceVariant }}>
                  <div className="flex justify-between gap-3"><dt>Format</dt><dd className="text-right font-medium" style={{ color: HOME_COLORS.onSurface }}>{INTERVIEW_TYPE_LABELS[interview?.type] ?? 'Interview'}</dd></div>
                  <div className="flex justify-between gap-3"><dt>Responses reviewed</dt><dd className="font-medium" style={{ color: HOME_COLORS.onSurface }}>{messageCount}</dd></div>
                  <div className="flex justify-between gap-3"><dt>Perspective</dt><dd className="text-right font-medium" style={{ color: HOME_COLORS.onSurface }}>{persona?.name ?? 'Research persona'}</dd></div>
                </dl>
                <p className="mt-4 pt-3 text-[11px] leading-relaxed" style={{ color: HOME_COLORS.onSurfaceVariant, borderTop: `1px solid ${accentLine}` }}>
                  Findings are directional and should be validated with real customers before material decisions are made.
                </p>
              </div>
            )}
          </div>
        </div>

        {isWhiteLabel && (
          <footer id="report-end" className="mt-10 border-t px-1 pt-5 pb-3 text-[10px] uppercase tracking-[0.14em]" style={{ borderColor: accentLine, color: HOME_COLORS.onSurfaceVariant }}>
            <div className="flex flex-wrap items-center justify-between gap-3">
              <span>Confidential research deliverable</span>
              {brandLogoUrl ? <>
                {/* eslint-disable-next-line @next/next/no-img-element -- tenant-provided Supabase logo URL */}
                <img src={brandLogoUrl} alt={`${brandName} logo`} className="h-5 w-auto object-contain" />
              </> : <span>{brandName}</span>}
            </div>
          </footer>
        )}
      </div>
    </div>
  )
}

// ─── Recommendation card ───────────────────────────────────────────────────────

function RecommendationCard({ rec, accentColor }: { rec: ReportRecommendation; accentColor?: string }) {
  const priorityClass = getPriorityColor(rec.priority)
  const PriorityIcon = rec.priority === 'high' ? AlertCircle
    : rec.priority === 'medium' ? Info
    : CheckCircle2

  return (
    <div className="rounded-2xl p-5" style={accentColor ? { ...cardStyle, borderLeft: `3px solid ${accentColor}` } : cardStyle}>
      <div className="flex items-start gap-3">
        <div className={`flex-shrink-0 mt-0.5 p-1 rounded-md ${priorityClass}`}>
          <PriorityIcon size={13} />
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1">
            <h3 className="text-sm font-semibold" style={{ color: HOME_COLORS.onSurface }}>{rec.title}</h3>
            <span className={`text-[11px] font-medium px-2 py-0.5 rounded-full capitalize ${priorityClass}`}>
              {rec.priority}
            </span>
          </div>
          <p className="text-sm leading-relaxed" style={{ color: HOME_COLORS.onSurfaceVariant }}>{rec.detail}</p>
        </div>
      </div>
    </div>
  )
}

function CoverMetric({ label, value }: { label: string; value: string }) {
  return (
    <div className="min-w-0 pr-3">
      <p className="text-[10px] font-semibold uppercase tracking-[0.13em] mb-1" style={{ color: HOME_COLORS.onSurfaceVariant }}>{label}</p>
      <p className="truncate text-sm font-semibold" style={{ color: HOME_COLORS.onSurface }}>{value}</p>
    </div>
  )
}

// ─── Confidence bar ────────────────────────────────────────────────────────────

function ConfidenceBar({ label, value, accentColor }: { label: string; value: number; accentColor: string }) {
  const capped = Math.min(100, Math.max(0, value))
  const color = capped >= 75 ? accentColor : capped >= 50 ? '#D97706' : '#EF4444'

  return (
    <div>
      <div className="flex justify-between text-xs mb-1">
        <span style={{ color: HOME_COLORS.onSurfaceVariant }}>{label}</span>
        <span className="font-medium" style={{ color: HOME_COLORS.onSurface }}>{capped}%</span>
      </div>
      <div className="h-1.5 rounded-full overflow-hidden" style={{ background: HOME_COLORS.surfaceContainer }}>
        <div className="h-1.5 rounded-full transition-all" style={{ width: `${capped}%`, background: color }} />
      </div>
    </div>
  )
}

// ─── Sentiment breakdown ───────────────────────────────────────────────────────

function SentimentBreakdown({ themes, accentColor }: { themes: ReportTheme[]; accentColor: string }) {
  const counts = themes.reduce((acc, t) => {
    acc[t.sentiment] = (acc[t.sentiment] ?? 0) + 1
    return acc
  }, {} as Record<string, number>)

  const total = themes.length
  const sentiments: { key: string; label: string; color: string }[] = [
    { key: 'positive', label: 'Positive', color: accentColor },
    { key: 'mixed', label: 'Mixed', color: '#D97706' },
    { key: 'neutral', label: 'Neutral', color: HOME_COLORS.outline },
    { key: 'negative', label: 'Negative', color: '#EF4444' },
  ]

  return (
    <div className="space-y-2.5">
      {sentiments.filter(s => counts[s.key]).map(s => {
        const count = counts[s.key] ?? 0
        const pct = Math.round((count / total) * 100)
        return (
          <div key={s.key}>
            <div className="flex justify-between text-xs mb-1">
              <span style={{ color: s.color }}>{s.label}</span>
              <span style={{ color: HOME_COLORS.onSurfaceVariant }}>{count} theme{count !== 1 ? 's' : ''}</span>
            </div>
            <div className="h-1.5 rounded-full overflow-hidden" style={{ background: HOME_COLORS.surfaceContainer }}>
              <div className="h-1.5 rounded-full" style={{ width: `${pct}%`, background: s.color }} />
            </div>
          </div>
        )
      })}
    </div>
  )
}

// ─── Helpers ───────────────────────────────────────────────────────────────────

function getPersonaSpecificity(persona: Pick<Persona, 'traits'> | null | undefined): number {
  if (!persona?.traits) return 30
  const t = persona.traits
  let score = 0
  if (t.job_title) score += 15
  if (t.location) score += 10
  if (t.goals?.filter(Boolean).length > 0) score += 20
  if (t.frustrations?.filter(Boolean).length > 0) score += 20
  if (t.buying_behavior) score += 20
  if (t.additional_context) score += 15
  return Math.min(100, score)
}

function withAlpha(hex: string, alpha: number) {
  const normalized = /^#[0-9a-fA-F]{6}$/.test(hex) ? hex : HOME_COLORS.primary
  const value = parseInt(normalized.slice(1), 16)
  const red = (value >> 16) & 255
  const green = (value >> 8) & 255
  const blue = value & 255
  return `rgba(${red}, ${green}, ${blue}, ${alpha})`
}
