import { notFound } from 'next/navigation'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'
import { formatDate, getPriorityColor, INTERVIEW_TYPE_LABELS, CARD_SHADOW } from '@/lib/utils'
import { HOME_COLORS, HOME_FONT_DISPLAY, HOME_FONT_BODY, DISPLAY_LG_STYLE } from '@/lib/home-theme'
import { ArrowLeft, BarChart3, CheckCircle2, Info, Lightbulb, MessageSquare, Share2, Sparkles } from 'lucide-react'
import { PersonaAvatar } from '@/components/persona/PersonaAvatar'
import { DownloadReportButton } from '@/components/ui/DownloadReportButton'
import { CopyLinkButton } from '@/components/ui/CopyLinkButton'
import { AutoPrint } from '@/components/ui/AutoPrint'
import { ThemesClient } from './ThemesClient'
import type { ReportTheme, ReportRecommendation } from '@/types'

const cardStyle = { background: HOME_COLORS.surfaceContainerLowest, boxShadow: CARD_SHADOW }

export default async function ReportPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ print?: string }> }) {
  const { id } = await params
  const { print } = await searchParams
  const supabase = await createClient()
  const { data: report, error } = await supabase.from('reports').select(`*, interview:interviews(id, title, type, context, messages, created_at, persona:personas(*))`).eq('id', id).single()
  if (error || !report) notFound()
  const interview = report.interview
  const persona = interview?.persona
  const score = report.confidence_score ?? 0
  const scoreColor = score >= 75 ? HOME_COLORS.primary : score >= 50 ? '#B45309' : HOME_COLORS.error
  const scoreLabel = score >= 75 ? 'High' : score >= 50 ? 'Moderate' : 'Low'
  const themes: ReportTheme[] = report.key_themes ?? []
  const recommendations: ReportRecommendation[] = report.recommendations ?? []
  const messageCount = interview?.messages?.length ?? 0
  const topRecommendation = recommendations[0]

  return <div className="report-detail-print min-h-full pb-20" style={{ background: '#f9f9f8', fontFamily: HOME_FONT_BODY }}>
    <AutoPrint trigger={print === '1'} />
    <div className="mx-auto max-w-[1440px] px-5 pt-7 sm:px-10 sm:pt-10">
      <Link href="/reports" className="group mb-10 inline-flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.16em] transition-colors hover:text-[#18281c]" style={{ color: HOME_COLORS.onSurfaceVariant }}><ArrowLeft size={17} className="transition-transform group-hover:-translate-x-1" />All reports</Link>
      <section className="mb-10">
        <div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-start">
          <div className="min-w-0 flex-1">
            <div className="flex items-center gap-5">
              <div className="relative shrink-0"><PersonaAvatar avatarUrl={persona?.avatar_url} avatarInitials={persona?.avatar_initials} avatarColor={persona?.avatar_color} name={persona?.name} size="xl" /><span className="absolute -bottom-1 -right-1 flex h-6 w-6 items-center justify-center rounded-full border-2" style={{ background: HOME_COLORS.primary, color: HOME_COLORS.onPrimary, borderColor: HOME_COLORS.surface }}><CheckCircle2 size={13} /></span></div>
              <div className="min-w-0"><h1 className="mb-2" style={{ ...DISPLAY_LG_STYLE, fontSize: 'clamp(24px, 3vw, 32px)', lineHeight: 1.15, color: HOME_COLORS.onSurface }}>{interview?.title ?? 'Untitled interview'}</h1><div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-sm" style={{ color: HOME_COLORS.onSurfaceVariant }}><strong style={{ color: HOME_COLORS.onSurface }}>{persona?.name ?? 'Research participant'}</strong><span>•</span><span>{INTERVIEW_TYPE_LABELS[interview?.type] ?? 'Interview'}</span><span>•</span><span>{formatDate(report.created_at)}</span></div></div>
            </div>
            {interview?.context && <p className="mt-7 max-w-3xl text-base leading-relaxed" style={{ color: HOME_COLORS.onSurfaceVariant }}>{interview.context}</p>}
          </div>
          <div className="w-full rounded-xl border p-6 lg:w-72" style={{ background: HOME_COLORS.surfaceContainerLow, borderColor: `${HOME_COLORS.outlineVariant}33`, boxShadow: '0 2px 5px rgba(15,23,42,.04)' }}><div className="mb-4 flex items-center justify-between text-[11px] font-semibold uppercase tracking-wider" style={{ color: HOME_COLORS.onSurfaceVariant }}>Confidence score <span className="group relative flex cursor-help"><Info size={15} /><span className="pointer-events-none absolute right-0 top-6 z-20 w-52 rounded-lg px-3 py-2 text-[11px] font-normal normal-case leading-relaxed opacity-0 shadow-lg transition-opacity group-hover:opacity-100" style={{background:HOME_COLORS.primary,color:HOME_COLORS.onPrimary}}>Measures response depth and persona specificity. It is not a market-certainty score.</span></span></div><div className="flex items-baseline gap-2"><span className="text-4xl" style={{ color: scoreColor, fontFamily: HOME_FONT_DISPLAY, fontWeight: 600 }}>{score}%</span><span className="text-[11px] font-semibold uppercase" style={{ color: scoreColor }}>{scoreLabel}</span></div><div className="mt-4 h-1.5 overflow-hidden rounded-full" style={{ background: HOME_COLORS.surfaceContainer }}><div className="h-full rounded-full" style={{ width: `${score}%`, background: scoreColor }} /></div><p className="mt-4 text-xs italic leading-relaxed" style={{ color: HOME_COLORS.onSurfaceVariant }}>Confidence reflects the depth and specificity of this interview.</p></div>
        </div>
        <div className="mt-10 flex flex-wrap items-center gap-3"><DownloadReportButton variant="primary" /><span className="inline-flex items-center rounded-lg bg-[#eae7e7] px-5 py-2.5 text-sm font-medium transition-colors hover:bg-[#dedbda]" style={{ color: HOME_COLORS.onSurface }}><Share2 size={18} className="mr-2" /><CopyLinkButton reportId={report.id} initialShared={!!report.share_token} variant="action" /></span><Link href={`/interviews/${interview?.id}`} className="inline-flex items-center rounded-lg bg-[#eae7e7] px-5 py-2.5 text-sm font-medium transition-colors hover:bg-[#dedbda]" style={{ color: HOME_COLORS.onSurface }}><MessageSquare size={18} className="mr-2" />View full transcript</Link></div>
      </section>
    </div>
    <section className="mb-12 grid grid-cols-1 divide-y border-y md:grid-cols-3 md:divide-x md:divide-y-0" style={{ borderColor: `${HOME_COLORS.outlineVariant}77` }}>{[[themes.length,'Key themes identified'],[recommendations.length,'Recommendations'],[messageCount,'Critical messages']].map(([value,label]) => <div key={String(label)} className="flex flex-col items-center bg-[#f9f9f8] px-8 py-8 text-center"><span className="text-4xl" style={{ color: HOME_COLORS.primary, fontFamily: HOME_FONT_DISPLAY, fontWeight: 600 }}>{value}</span><span className="mt-1 text-[10px] font-semibold uppercase tracking-[0.15em]" style={{ color: HOME_COLORS.onSurfaceVariant }}>{label}</span></div>)}</section>
    <div className="mx-auto grid max-w-[1440px] grid-cols-1 gap-8 px-5 sm:px-10 lg:grid-cols-12"><main className="space-y-8 lg:col-span-8">
      {report.ai_verdict && <section className="relative overflow-hidden rounded-2xl p-7 sm:p-8" style={{ background: '#dfe4da' }}><BarChart3 className="absolute right-5 top-5 h-12 w-12 opacity-[.12]" style={{color:'#182820'}} /><div className="relative"><h2 className="mb-5 flex items-center gap-2 text-xl" style={{ color: '#182820', fontFamily: HOME_FONT_DISPLAY, fontWeight: 600 }}><Sparkles size={20} />AI Summary</h2><p className="text-base leading-relaxed" style={{ color: '#1a1c1c' }}>{report.ai_verdict.summary}</p><div className="mt-7 grid gap-7 md:grid-cols-2"><Brief label="Validate next" value={report.ai_verdict.validate_next} icon="check" /><Brief label="Ask real users" value={`“${report.ai_verdict.follow_up_question}”`} icon="ask" /></div></div></section>}
      <section className="rounded-2xl p-7 sm:p-8" style={cardStyle}><h2 className="mb-5 text-xl" style={{ color: HOME_COLORS.onSurface, fontFamily: HOME_FONT_DISPLAY, fontWeight: 600 }}>Executive Summary</h2><p className="text-base leading-relaxed" style={{ color: HOME_COLORS.onSurfaceVariant }}>{report.executive_summary}</p></section>
      {themes.length > 0 && <section className="space-y-6"><h2 className="text-xl" style={{ color: HOME_COLORS.onSurface, fontFamily: HOME_FONT_DISPLAY, fontWeight: 600 }}>Key Themes</h2><ThemesClient themes={themes} confidenceScore={score} variant="report-detail" /></section>}
      {recommendations.length > 0 && <section className="space-y-5"><h2 className="text-xl" style={{ color: HOME_COLORS.onSurface, fontFamily: HOME_FONT_DISPLAY, fontWeight: 600 }}>Recommendations</h2>{recommendations.map((rec,i)=><RecommendationCard key={i} rec={rec} index={i} />)}</section>}
    </main><aside className="space-y-6 lg:col-span-4"><ScoreCard label="About this score"><ConfidenceBar label="Depth of responses" value={Math.min(100,messageCount*12)} /><ConfidenceBar label="Persona specificity" value={getPersonaSpecificity(persona)} /><p className="mt-6 text-xs leading-relaxed" style={{ color: HOME_COLORS.onSurfaceVariant }}>The score reflects a specific participant and detailed responses—not market certainty.</p></ScoreCard>{themes.length>0&&<ScoreCard label="Sentiment breakdown"><SentimentBreakdown themes={themes}/></ScoreCard>}{persona&&<PersonaCard persona={persona}/>} {topRecommendation&&<section className="rounded-2xl p-6" style={{ background: HOME_COLORS.primary, color: HOME_COLORS.onPrimary, boxShadow: '0 12px 28px rgba(24,40,28,.16)' }}><Lightbulb size={20} className="mb-4"/><h2 className="text-xl" style={{fontFamily:HOME_FONT_DISPLAY,fontWeight:600}}>Key Recommendation</h2><p className="mt-2 text-sm leading-relaxed opacity-85">{topRecommendation.detail}</p></section>}</aside></div>
  </div>
}
function Brief({label,value,icon}:{label:string;value:string;icon:string}){return <div><h3 className="mb-3 text-[11px] font-semibold uppercase tracking-wider" style={{color:HOME_COLORS.primary}}>{label}</h3><p className="flex gap-2 text-sm leading-relaxed" style={{color:HOME_COLORS.onSurface}}><span>{icon==='check'?'✓':'?'}</span>{value}</p></div>}
function ScoreCard({label,children}:{label:string;children:React.ReactNode}){return <section className="rounded-2xl p-6" style={cardStyle}><h2 className="mb-6 text-[11px] font-semibold uppercase tracking-[.15em]" style={{color:HOME_COLORS.onSurfaceVariant}}>{label}</h2><div className="space-y-5">{children}</div></section>}
function PersonaCard({persona}:{persona:any}){return <section className="overflow-hidden rounded-2xl" style={cardStyle}><div className="p-6"><h2 className="mb-6 text-[11px] font-semibold uppercase tracking-[.15em]" style={{color:HOME_COLORS.onSurfaceVariant}}>Interviewed</h2><div className="mb-6 flex items-center gap-4"><PersonaAvatar avatarUrl={persona.avatar_url} avatarInitials={persona.avatar_initials} avatarColor={persona.avatar_color} name={persona.name} size="lg"/><div><p className="text-lg" style={{fontFamily:HOME_FONT_DISPLAY,fontWeight:600}}>{persona.name}</p><p className="text-sm" style={{color:HOME_COLORS.onSurfaceVariant}}>{persona.traits?.job_title}</p></div></div><dl className="space-y-3 text-sm">{[['Age',persona.traits?.age],['Location',persona.traits?.location],['Industry',persona.traits?.industry]].filter(([,v])=>v).map(([l,v])=><div className="flex justify-between border-b pb-3" style={{borderColor:`${HOME_COLORS.outlineVariant}33`}} key={String(l)}><dt style={{color:HOME_COLORS.onSurfaceVariant}}>{l}</dt><dd className="font-medium">{String(v)}</dd></div>)}</dl></div><Link href={`/personas/${persona.id}`} className="block bg-[#f0eded] py-4 text-center text-[11px] font-semibold uppercase tracking-wider text-[#18281c] transition-all duration-300 hover:bg-[#18281c] hover:text-white">View full persona</Link></section>}
function RecommendationCard({rec,index}:{rec:ReportRecommendation;index:number}){return <div className="rounded-2xl border p-7 transition-all duration-300 hover:-translate-y-1 hover:shadow-[0_14px_30px_rgba(24,40,28,0.08)]" style={{...cardStyle,borderColor:`${HOME_COLORS.outlineVariant}2b`}}><div className="flex items-start gap-4"><span className="mt-0.5 text-3xl leading-none" style={{color:HOME_COLORS.outlineVariant,fontFamily:HOME_FONT_DISPLAY}}>{String(index+1).padStart(2,'0')}</span><div><p className="mb-2 text-[10px] font-semibold uppercase tracking-wider" style={{color:HOME_COLORS.onSurfaceVariant}}>{rec.priority} priority</p><h3 className="text-xl leading-tight" style={{fontFamily:HOME_FONT_DISPLAY,fontWeight:600}}>{rec.title}</h3><p className="mt-3 text-sm leading-relaxed" style={{color:HOME_COLORS.onSurfaceVariant}}>{rec.detail}</p></div></div></div>}
function ConfidenceBar({label,value}:{label:string;value:number}){const n=Math.min(100,Math.max(0,value));return <div><div className="mb-2 flex justify-between text-sm"><span className="font-medium">{label}</span><span style={{color:HOME_COLORS.primary}}>{n}%</span></div><div className="h-1.5 overflow-hidden rounded-full" style={{background:HOME_COLORS.surfaceContainer}}><div className="h-full rounded-full" style={{width:`${n}%`,background:HOME_COLORS.primary}}/></div></div>}
function SentimentBreakdown({themes}:{themes:ReportTheme[]}){const counts=themes.reduce((a,t)=>{a[t.sentiment]=(a[t.sentiment]??0)+1;return a},{} as Record<string,number>);return <>{(['positive','mixed','neutral','negative'] as const).filter(s=>counts[s]).map(s=>{const p=Math.round(counts[s]/themes.length*100);return <div className="flex items-center gap-3" key={s}><span className="w-20 text-sm capitalize">{s}</span><div className="h-2 flex-1 overflow-hidden rounded-full" style={{background:HOME_COLORS.surfaceContainer}}><div className="h-full" style={{width:`${p}%`,background:s==='positive'?HOME_COLORS.primary:s==='negative'?HOME_COLORS.tertiary:HOME_COLORS.outline}}/></div><span className="w-8 text-right text-xs font-semibold">{p}%</span></div>})}</>}
function getPersonaSpecificity(persona:any){if(!persona?.traits)return 30;const t=persona.traits;return Math.min(100,(t.job_title?15:0)+(t.location?10:0)+(t.goals?.filter(Boolean).length?20:0)+(t.frustrations?.filter(Boolean).length?20:0)+(t.buying_behavior?20:0)+(t.additional_context?15:0))}
